version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: ${DB_HOST}
    environment:
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - ${DB_PORT}:3306
    volumes:
      - ./db:/var/lib/mysql
      - ./mysql/beer_structure.sql:/docker-entrypoint-initdb.d/1_beer_structure.sql
      - ./mysql/beer_data.sql:/docker-entrypoint-initdb.d/2_beer_data.sql
    networks:
      - app-network
    restart: always

  app:
    build: .
    container_name: ${APP_HOST}
    ports:
      - ${APP_PORT}:3000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mysql
    networks:
      - app-network
  
networks:
  app-network:
    driver: bridge

