INSERT INTO cerveza (id_cerveza, nombre_cerveza, clase, marca, origen, graduacion)
VALUES
    (1, 'Aker IPA', 'IPA', 'Akerbeltz', 'Vizcaya', '6.5%'),
    (2, 'Akerbeltz / Ales Agullons AK60', 'Lambic - Fruit', 'Akerbeltz', 'Vizcaya', '6.0%'),
    (3, 'Akerbeltz / Bidassoa Rosabel', 'Belgian Witbier', 'Akerbeltz', 'Vizcaya', '4.8%'),
    (4, 'Akerbeltz Black', 'Stout', 'Akerbeltz', 'Vizcaya', '5.0%'),
    (5, 'Akerbeltz Crianza', 'Belgian Strong Ale', 'Akerbeltz', 'Vizcaya', '7.5%'),
    (6, 'Akerbeltz Porter', 'Porter', 'Akerbeltz', 'Vizcaya', '6.0%'),
    (7, 'Akerbeltz Porter Ahumada', 'Smoked Porter', 'Akerbeltz', 'Vizcaya', '6.0%'),
    (8, 'Akerbeltz Sorgin', 'Scottish Ale', 'Akerbeltz', 'Vizcaya', '5.0%'),
    (9, 'Akerbeltz Stout', 'Stout', 'Akerbeltz', 'Vizcaya', '6.5%'),
    (10, 'Akerbeltz Super', 'Extra Special Bitter', 'Akerbeltz', 'Vizcaya', '6.0%'),
    (11, 'Arriaca IPA', 'IPA', 'Arriaca', 'Guipúzcoa', '6.5%'),
    (12, 'Basqueland / Against The Grain 35K', 'Milk Stout', 'Basqueland Brewing', 'Guipúzcoa', '7.0%'),
    (13, 'Basqueland / Funky Fluid Pastry Axe Murderer', 'Pastry Stout', 'Basqueland Brewing', 'Guipúzcoa', '12.0%'),
    (14, 'Basqueland / La Pirata Daddys Home', 'American Barleywine', 'Basqueland Brewing', 'Guipúzcoa', '11.5%'),
    (15, 'Basqueland Arraun', 'Kölsch', 'Basqueland Brewing', 'Guipúzcoa', '4.8%'),
    (16, 'Basqueland AUPA TROPICANA!', 'Tropical IPA', 'Basqueland Brewing', 'Guipúzcoa', '6.5%'),
    (17, 'Basqueland Basajaun', 'Brown Ale', 'Basqueland Brewing', 'Guipúzcoa', '5.8%'),
    (18, 'Basqueland Blondie', 'Blonde Ale', 'Basqueland Brewing', 'Guipúzcoa', '4.8%'),
    (19, 'Basqueland Cashmere Sweater', 'Session IPA', 'Basqueland Brewing', 'Guipúzcoa', '4.2%'),
    (20, 'Basqueland Coco Chango', 'American Porter', 'Basqueland Brewing', 'Guipúzcoa', '6.5%'),
    (21, 'Basqueland Gala', 'Saison', 'Basqueland Brewing', 'Guipúzcoa', '5.8%'),
    (22, 'Basqueland Ghost Rider', 'Black IPA', 'Basqueland Brewing', 'Guipúzcoa', '6.2%'),
    (23, 'Basqueland Happy Place', 'IPA', 'Basqueland Brewing', 'Guipúzcoa', '6.0%'),
    (24, 'Basqueland Hop Fiction', 'American Pale Ale', 'Basqueland Brewing', 'Guipúzcoa', '5.5%'),
    (25, 'Basqueland Hopverdose', 'Triple IPA', 'Basqueland Brewing', 'Guipúzcoa', '10.5%'),
    (26, 'Basqueland Imparable', 'Double IPA', 'Basqueland Brewing', 'Guipúzcoa', '8.0%'),
    (27, 'Basqueland Imparable Hazy', 'New England IPA', 'Basqueland Brewing', 'Guipúzcoa', '6.5%'),
    (28, 'Basqueland Imparable XPA', 'Extra Pale Ale', 'Basqueland Brewing', 'Guipúzcoa', '4.5%'),
    (29, 'Basqueland Surf Rider', 'Session IPA', 'Basqueland Brewing', 'Guipúzcoa', '4.5%'),
    (30, 'Basqueland The Room', 'Imperial Stout', 'Basqueland Brewing', 'Guipúzcoa', '12.0%'),
    (31, 'Bidassoa Basque Brewery West Coast', 'West Coast IPA', 'Bidassoa', 'Guipúzcoa', '7.0%'),
    (32, 'Dougalls 942', 'American Pale Ale', 'Dougalls', 'Vizcaya', '4.2%'),
    (33, 'Dougalls Happy Otter', 'American Pale Ale', 'Dougalls', 'Vizcaya', '5.5%'),
    (34, 'Laugar / Jackie Os Choco Frappuccino', 'Imperial Stout', 'Laugar', 'Vizcaya', '11.5%'),
    (35, 'Laugar / Pipeworks All Titans Must Die', 'Imperial Stout', 'Laugar', 'Vizcaya', '11.0%'),
    (36, 'Laugar / Pohjala Real Estate', 'Imperial Stout', 'Laugar', 'Vizcaya', '12.0%'),
    (37, 'Laugar Aupa Tovarisch', 'Russian Imperial Stout', 'Laugar', 'Vizcaya', '10.0%'),
    (38, 'Laugar Bee Beer', 'Blonde Ale', 'Laugar', 'Vizcaya', '4.8%'),
    (39, 'Laugar Black Milk', 'Sweet Stout', 'Laugar', 'Vizcaya', '7.0%'),
    (40, 'Laugar Marti', 'Bière de Garde', 'Laugar', 'Vizcaya', '7.0%'),
    (41, 'Laugar The Bellman', 'American Pale Ale', 'Laugar', 'Vizcaya', '5.5%'),
    (42, 'Laugar The Knife', 'Imperial Stout', 'Laugar', 'Vizcaya', '11.0%'),
    (43, 'Laugar To Ol Fred', 'Barleywine', 'Laugar', 'Vizcaya', '12.0%'),
    (44, 'Laugar Wookie', 'American Brown Ale', 'Laugar', 'Vizcaya', '6.2%'),
    (45, 'Mala Gissona', 'Belgian Strong Ale', 'Mala Gissona', 'Vizcaya', '7.0%'),
    (46, 'Naparbier / Basqueland / De Molen Collaboration', 'Imperial Stout', 'Naparbier', 'Navarra', '11.0%'),
    (47, 'Naparbier / La Quince / Nómada Salt Lick', 'Gose', 'Naparbier', 'Navarra', '4.0%'),
    (48, 'Naparbier Aotearoa', 'New Zealand IPA', 'Naparbier', 'Navarra', '6.5%'),
    (49, 'Naparbier Back in Black', 'Black IPA', 'Naparbier', 'Navarra', '7.0%'),
    (50, 'Naparbier Back to Basqueland', 'American Pale Ale', 'Naparbier', 'Navarra', '5.5%'),
    (51, 'Naparbier Hop Doom', 'Double IPA', 'Naparbier', 'Navarra', '8.0%'),
    (52, 'Naparbier Hop Harvest', 'Harvest Ale', 'Naparbier', 'Navarra', '6.5%'),
    (53, 'Naparbier Oneka', 'American Pale Ale', 'Naparbier', 'Navarra', '4.5%'),
    (54, 'Naparbier Satanic Mills', 'Black IPA', 'Naparbier', 'Navarra', '7.5%'),
    (55, 'Naparbier White Riot', 'Witbier', 'Naparbier', 'Navarra', '4.5%'),
    (56, 'Naparbier Zombination', 'Imperial IPA', 'Naparbier', 'Navarra', '9.0%');