-- MySQL Script generated by MySQL Workbench
-- Mon Jul 17 17:07:59 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema euskalbeer
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `euskalbeer` ;

-- -----------------------------------------------------
-- Schema euskalbeer
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `euskalbeer` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `euskalbeer` ;

-- -----------------------------------------------------
-- Table `euskalbeer`.`cerveza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `euskalbeer`.`cerveza` (
  `id_cerveza` INT UNSIGNED NOT NULL,
  `nombre_cerveza` VARCHAR(60) NOT NULL,
  `clase` VARCHAR(45) NOT NULL,
  `marca` VARCHAR(45) NOT NULL,
  `origen` VARCHAR(45) NOT NULL,
  `graduacion` VARCHAR(6) NOT NULL,
  PRIMARY KEY (`id_cerveza`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `euskalbeer`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `euskalbeer`.`usuarios` (
  `id_usuario` VARCHAR(100) NOT NULL,
  `usuario_mail` VARCHAR(60) NOT NULL,
  `password` VARCHAR(80) NOT NULL,
  `Favoritos` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `contraseÃ±a_UNIQUE` (`password` ASC) VISIBLE,
  UNIQUE INDEX `usuario_mail_UNIQUE` (`usuario_mail` ASC) VISIBLE,
  UNIQUE INDEX `id_usuario_UNIQUE` (`id_usuario` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `euskalbeer`.`cerveza_has_usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `euskalbeer`.`cerveza_has_usuarios` (
  `id_cerveza` INT UNSIGNED NOT NULL,
  `id_usuario` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_cerveza`, `id_usuario`),
  UNIQUE INDEX `id_cerveza_UNIQUE` (`id_cerveza` ASC) VISIBLE,
  INDEX `fk_cerveza_has_usuarios_usuarios1_idx` (`id_usuario` ASC) VISIBLE,
  INDEX `fk_cerveza_has_usuarios_cerveza1_idx` (`id_cerveza` ASC) VISIBLE,
  CONSTRAINT `fk_cerveza_has_usuarios_cerveza1`
    FOREIGN KEY (`id_cerveza`)
    REFERENCES `euskalbeer`.`cerveza` (`id_cerveza`),
  CONSTRAINT `fk_cerveza_has_usuarios_usuarios1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `euskalbeer`.`usuarios` (`id_usuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
